import React, { useState, useEffect, useMemo } from 'react';
import {
  IonPage,
  IonHeader,
  IonToolbar,
  IonTitle,
  IonContent,
  IonCard,
  IonCardHeader,
  IonCardTitle,
  IonCardSubtitle,
  IonCardContent,
  IonSegment,
  IonSegmentButton,
  IonLabel,
  IonItem,
  IonSelect,
  IonSelectOption,
  IonSpinner,
  IonText,
  IonIcon,
  IonGrid,
  IonRow,
  IonCol,
  IonList,
  IonListHeader
} from '@ionic/react';
import {
  barChartOutline,
  analyticsOutline,
  timeOutline,
  filterOutline,
  alertCircleOutline,
  schoolOutline,
  ribbonOutline
} from 'ionicons/icons';
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
  ScatterChart,
  Scatter,
  ZAxis,
  LineChart,
  Line
} from 'recharts';
import api from '../api'; // central API helper built in previous steps
import 'dotenv/config';

import { faker } from '@faker-js/faker';

// TypeScript structures for relational data coming from database/seed.ts
interface School {
  id: string;
  name: string;
}

interface Program {
  id: string;
  name: string;
  degreeLevel: 'Masters' | 'Doctoral';
}

interface Decision {
  id: string;
  status: 'ACCEPTED' | 'REJECTED' | 'WAITLISTED';
  decisionDate: string; // ISO string
}

interface Application {
  id: string;
  gpa: number;
  publications: number;
  school: School;
  program: Program;
  decision: Decision | null;
}

const AnalyticsDashboard: React.FC = () => {
  // Navigation tabs (to switch charts and avoid line overload)
  const [activeTab, setActiveTab] = useState<'rates' | 'scatter' | 'timeline'>('rates');

  // Master applications list fetched from DB
  const [applications, setApplications] = useState<Application[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  // Filter selection states
  const [selectedSchool, setSelectedSchool] = useState<string>('ALL');
  const [selectedProgram, setSelectedProgram] = useState<string>('ALL');

  // Fetch data on mount
  useEffect(() => {
    const loadAnalyticsData = async () => {
      setLoading(true);
      setError(null);
      try {
        // Fetch all community applications
        const data = await api.get<Application[]>('/applications');
        setApplications(data);
      } catch (err: any) {
        console.error('Failed to load applications for charts:', err);
        // Fallback to mock data generated by your seed schema if backend is offline
        setApplications(generateFallbackMockData());
      } finally {
        setLoading(false);
      }
    };

    loadAnalyticsData();
  }, []);

  // --- FILTER EXTENSIONS ---
  // Extract unique schools and programs from dataset to populate filters dynamically
  const uniqueSchools = useMemo(() => {
    const list = new Set(applications.map((app) => app.school.name));
    return Array.from(list).sort();
  }, [applications]);

  const uniquePrograms = useMemo(() => {
    const list = new Set(applications.map((app) => app.program.name));
    return Array.from(list).sort();
  }, [applications]);

  // Filter the master list based on dropdown selections
  const filteredApplications = useMemo(() => {
    return applications.filter((app) => {
      const matchSchool = selectedSchool === 'ALL' || app.school.name === selectedSchool;
      const matchProgram = selectedProgram === 'ALL' || app.program.name === selectedProgram;
      return matchSchool && matchProgram;
    });
  }, [applications, selectedSchool, selectedProgram]);

  // --- CHART DATA COMPILERS (Aggregated client-side on filtered data) ---

  // 1. Acceptance Breakdown data
  const acceptanceRateData = useMemo(() => {
    let accepted = 0;
    let rejected = 0;
    let waitlisted = 0;
    let pending = 0;

    filteredApplications.forEach((app) => {
      if (!app.decision) {
        pending++;
      } else if (app.decision.status === 'ACCEPTED') {
        accepted++;
      } else if (app.decision.status === 'REJECTED') {
        rejected++;
      } else if (app.decision.status === 'WAITLISTED') {
        waitlisted++;
      }
    });

    const total = accepted + rejected + waitlisted + pending;
    if (total === 0) return [];

    return [
      { name: 'Accepted', count: accepted, percentage: Math.round((accepted / total) * 100), fill: '#2dd36f' },
      { name: 'Waitlisted', count: waitlisted, percentage: Math.round((waitlisted / total) * 100), fill: '#ffc409' },
      { name: 'Rejected', count: rejected, percentage: Math.round((rejected / total) * 100), fill: '#eb445a' },
      { name: 'Pending', count: pending, percentage: Math.round((pending / total) * 100), fill: '#92949c' }
    ];
  }, [filteredApplications]);

  // 2. GPA & Publications Competitiveness Scatter plot data
  const scatterPlotData = useMemo(() => {
    const acceptedData: any[] = [];
    const waitlistedData: any[] = [];
    const rejectedData: any[] = [];

    filteredApplications.forEach((app) => {
      if (app.decision) {
        const dataPoint = {
          gpa: Number(app.gpa),
          publications: app.publications,
          schoolName: app.school.name,
          programName: app.program.name
        };

        if (app.decision.status === 'ACCEPTED') {
          acceptedData.push(dataPoint);
        } else if (app.decision.status === 'WAITLISTED') {
          waitlistedData.push(dataPoint);
        } else if (app.decision.status === 'REJECTED') {
          rejectedData.push(dataPoint);
        }
      }
    });

    return {
      accepted: acceptedData,
      waitlisted: waitlistedData,
      rejected: rejectedData
    };
  }, [filteredApplications]);

  // 3. Decision timeline (Aggregates decision counts by month-year)
  const timelineData = useMemo(() => {
    const datesMap: { [key: string]: { accepted: number; rejected: number; waitlisted: number } } = {};

    filteredApplications.forEach((app) => {
      if (app.decision && app.decision.decisionDate) {
        // Format to YYYY-MM
        const dateObj = new Date(app.decision.decisionDate);
        if (isNaN(dateObj.getTime())) return;

        const monthName = dateObj.toLocaleString('en-US', { month: 'short', year: 'numeric' });

        if (!datesMap[monthName]) {
          datesMap[monthName] = { accepted: 0, rejected: 0, waitlisted: 0 };
        }

        if (app.decision.status === 'ACCEPTED') {
          datesMap[monthName].accepted++;
        } else if (app.decision.status === 'REJECTED') {
          datesMap[monthName].rejected++;
        } else if (app.decision.status === 'WAITLISTED') {
          datesMap[monthName].waitlisted++;
        }
      }
    });

    // Sort chronologically by converting keys back to Date objects for sorting
    return Object.keys(datesMap)
      .map((month) => ({
        month,
        Accepted: datesMap[month].accepted,
        Rejected: datesMap[month].rejected,
        Waitlisted: datesMap[month].waitlisted,
        total: datesMap[month].accepted + datesMap[month].rejected + datesMap[month].waitlisted,
        sortDate: new Date(month)
      }))
      .sort((a, b) => a.sortDate.getTime() - b.sortDate.getTime());
  }, [filteredApplications]);

  return (
    <IonPage>
      <IonHeader>
        <IonToolbar color="primary">
          <IonTitle>Admission Insights Dashboard</IonTitle>
        </IonToolbar>
      </IonHeader>

      <IonContent className="ion-padding" style={{ '--background': '#f4f5f8' }}>
        {/* Centralized Header */}
        <div style={{ textAlign: 'center', margin: '16px 0 24px 0' }}>
          <h2 style={{ fontWeight: '700', color: 'var(--ion-color-dark)', margin: '0 0 6px 0' }}>Community Analytics</h2>
          <p style={{ color: '#666', margin: '0', fontSize: '14px' }}>
            Overlay admissions decisions, timelines, and competitiveness metrics.
          </p>
        </div>

        {/* Dynamic Filters Section */}
        <IonCard style={{ margin: '0 0 20px 0', borderRadius: '12px', boxShadow: '0 4px 12px rgba(0,0,0,0.05)' }}>
          <IonCardContent className="ion-no-padding">
            <IonGrid>
              <IonRow className="ion-align-items-center">
                <IonCol size="12" sizeMd="6">
                  <IonItem lines="none">
                    <IonIcon icon={schoolOutline} slot="start" style={{ color: 'var(--ion-color-primary)' }} />
                    <IonSelect
                      label="Target University"
                      labelPlacement="stacked"
                      value={selectedSchool}
                      onIonChange={(e) => setSelectedSchool(e.detail.value)}
                    >
                      <IonSelectOption value="ALL">All Universities (Default)</IonSelectOption>
                      {uniqueSchools.map((school) => (
                        <IonSelectOption key={school} value={school}>
                          {school}
                        </IonSelectOption>
                      ))}
                    </IonSelect>
                  </IonItem>
                </IonCol>

                <IonCol size="12" sizeMd="6">
                  <IonItem lines="none">
                    <IonIcon icon={ribbonOutline} slot="start" style={{ color: 'var(--ion-color-primary)' }} />
                    <IonSelect
                      label="Academic Field"
                      labelPlacement="stacked"
                      value={selectedProgram}
                      onIonChange={(e) => setSelectedProgram(e.detail.value)}
                    >
                      <IonSelectOption value="ALL">All Programs (Default)</IonSelectOption>
                      {uniquePrograms.map((program) => (
                        <IonSelectOption key={program} value={program}>
                          {program}
                        </IonSelectOption>
                      ))}
                    </IonSelect>
                  </IonItem>
                </IonCol>
              </IonRow>
            </IonGrid>
          </IonCardContent>
        </IonCard>

        {/* Segment Tabs Control (Prevents multi-line overload by isolating charts) */}
        <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '20px' }}>
          <IonSegment
            value={activeTab}
            onIonChange={(e) => setActiveTab(e.detail.value as any)}
            style={{ maxWidth: '600px', backgroundColor: '#e0e2e9', borderRadius: '20px', padding: '2px' }}
          >
            <IonSegmentButton value="rates" style={{ '--border-radius': '18px' }}>
              <IonIcon icon={barChartOutline} style={{ marginRight: '6px' }} />
              <IonLabel style={{ fontSize: '12px' }}>Acceptance Rates</IonLabel>
            </IonSegmentButton>
            <IonSegmentButton value="scatter" style={{ '--border-radius': '18px' }}>
              <IonIcon icon={analyticsOutline} style={{ marginRight: '6px' }} />
              <IonLabel style={{ fontSize: '12px' }}>Competitiveness</IonLabel>
            </IonSegmentButton>
            <IonSegmentButton value="timeline" style={{ '--border-radius': '18px' }}>
              <IonIcon icon={timeOutline} style={{ marginRight: '6px' }} />
              <IonLabel style={{ fontSize: '12px' }}>Decision Waves</IonLabel>
            </IonSegmentButton>
          </IonSegment>
        </div>

        {/* Loading Spinner */}
        {loading && (
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '250px' }}>
            <IonSpinner name="crescent" color="primary" />
            <IonText color="medium" style={{ marginTop: '12px' }}>Loading real-time insights...</IonText>
          </div>
        )}

        {/* Main Graph Card Container */}
        {!loading && (
          <IonCard style={{ borderRadius: '16px', boxShadow: '0 6px 16px rgba(0,0,0,0.06)', margin: '0' }}>
            <IonCardHeader>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div>
                  <IonCardTitle style={{ fontSize: '18px', fontWeight: '700' }}>
                    {activeTab === 'rates' && 'Decision Status Ratios'}
                    {activeTab === 'scatter' && 'GPA vs Publications Spread'}
                    {activeTab === 'timeline' && 'Timeline of Released Decisions'}
                  </IonCardTitle>
                  <IonCardSubtitle>
                    Based on {filteredApplications.length} tracked community submissions
                  </IonCardSubtitle>
                </div>
              </div>
            </IonCardHeader>

            <IonCardContent style={{ height: '380px', padding: '16px' }}>
              {filteredApplications.length === 0 ? (
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', color: '#999' }}>
                  <IonIcon icon={filterOutline} style={{ fontSize: '48px', marginBottom: '12px' }} />
                  <p>No applications found matching your active filter criteria.</p>
                </div>
              ) : (
                <ResponsiveContainer width="100%" height="100%">
                  {/* CHART TABS */}

                  {/* TAB 1: ACCEPTANCE BAR CHART */}
                  {activeTab === 'rates' && (
                    <BarChart
                      data={acceptanceRateData}
                      margin={{ top: 10, right: 10, left: -20, bottom: 5 }}
                    >
                      <CartesianGrid strokeDasharray="3 3" vertical={false} />
                      <XAxis dataKey="name" tick={{ fontSize: '12px' }} />
                      <YAxis tick={{ fontSize: '12px' }} label={{ value: 'Percentage (%)', angle: -90, position: 'insideLeft', style: { textAnchor: 'middle', fontSize: '12px' } }} />
                      <Tooltip 
                        formatter={(value, name, props) => [`${value}% (${props.payload.count} apps)`, 'Share']} 
                        contentStyle={{ borderRadius: '8px', boxShadow: '0 2px 8px rgba(0,0,0,0.1)' }}
                      />
                      <Bar 
                        dataKey="percentage" 
                        radius={[8, 8, 0, 0]} 
                        maxBarSize={60}
                      />
                    </BarChart>
                  )}

                  {/* TAB 2: COMPETITIVENESS SCATTER PLOT */}
                  {activeTab === 'scatter' && (
                    <ScatterChart
                      margin={{ top: 20, right: 20, left: -10, bottom: 10 }}
                    >
                      <CartesianGrid strokeDasharray="3 3" />
                      <XAxis 
                        type="number" 
                        dataKey="gpa" 
                        name="GPA" 
                        domain={[2.5, 4.0]} 
                        tickCount={4}
                        label={{ value: 'GPA', position: 'bottom', offset: -5, style: { fontSize: '12px' } }} 
                      />
                      <YAxis 
                        type="number" 
                        dataKey="publications" 
                        name="Publications" 
                        domain={[0, 'dataMax + 1']}
                        label={{ value: 'Publications Count', angle: -90, position: 'insideLeft', style: { textAnchor: 'middle', fontSize: '12px' } }} 
                      />
                      <ZAxis type="number" range={[100, 100]} />
                      <Tooltip 
                        cursor={{ strokeDasharray: '3 3' }} 
                        content={({ active, payload }) => {
                          if (active && payload && payload.length) {
                            const data = payload[0].payload;
                            return (
                              <div style={{ backgroundColor: '#fff', padding: '10px', border: '1px solid #ccc', borderRadius: '8px', boxShadow: '0 2px 8px rgba(0,0,0,0.1)' }}>
                                <p style={{ margin: '0 0 4px 0', fontWeight: 'bold' }}>{data.schoolName}</p>
                                <p style={{ margin: '0 0 4px 0', fontSize: '12px' }}>Program: {data.programName}</p>
                                <p style={{ margin: '0 0 4px 0', fontSize: '12px' }}>GPA: {data.gpa}</p>
                                <p style={{ margin: '0', fontSize: '12px' }}>Publications: {data.publications}</p>
                              </div>
                            );
                          }
                          return null;
                        }}
                      />
                      <Legend verticalAlign="top" height={36} />
                      <Scatter name="Accepted" data={scatterPlotData.accepted} fill="#2dd36f" shape="circle" />
                      <Scatter name="Waitlisted" data={scatterPlotData.waitlisted} fill="#ffc409" shape="circle" />
                      <Scatter name="Rejected" data={scatterPlotData.rejected} fill="#eb445a" shape="circle" />
                    </ScatterChart>
                  )}

                  {/* TAB 3: TIMELINE LINE CHART (Single-line chronological mapping to show decision waves) */}
                  {activeTab === 'timeline' && (
                    <LineChart
                      data={timelineData}
                      margin={{ top: 10, right: 20, left: -20, bottom: 5 }}
                    >
                      <CartesianGrid strokeDasharray="3 3" vertical={false} />
                      <XAxis dataKey="month" tick={{ fontSize: '12px' }} />
                      <YAxis tick={{ fontSize: '12px' }} />
                      <Tooltip contentStyle={{ borderRadius: '8px', boxShadow: '0 2px 8px rgba(0,0,0,0.1)' }} />
                      <Legend verticalAlign="top" height={36} />
                      {/* Separate clean single lines to prevent visual clutter */}
                      <Line type="monotone" dataKey="Accepted" stroke="#2dd36f" strokeWidth={3} activeDot={{ r: 8 }} dot={{ r: 4 }} />
                      <Line type="monotone" dataKey="Waitlisted" stroke="#ffc409" strokeWidth={2} dot={{ r: 4 }} />
                      <Line type="monotone" dataKey="Rejected" stroke="#eb445a" strokeWidth={2} dot={{ r: 4 }} />
                    </LineChart>
                  )}
                </ResponsiveContainer>
              )}
            </IonCardContent>
          </IonCard>
        )}
      </IonContent>
    </IonPage>
  );
};

// Fallback Mock Data matching the DB structures to prevent crash when backend/Postgres is offline
const generateFallbackMockData = (): Application[] => {
  const dummyPrograms: Program[] = [
    { id: 'p1', name: 'Computer Science', degreeLevel: 'Doctoral' },
    { id: 'p2', name: 'Data Science', degreeLevel: 'Masters' },
    { id: 'p3', name: 'Cybersecurity', degreeLevel: 'Masters' }
  ];

  const dummySchools: School[] = [
    { id: 's1', name: 'MIT' },
    { id: 's2', name: 'Stanford University' },
    { id: 's3', name: 'Carnegie Mellon University' }
  ];

  const statuses: ('ACCEPTED' | 'REJECTED' | 'WAITLISTED')[] = ['ACCEPTED', 'REJECTED', 'WAITLISTED'];
  const dates = [
    '2026-02-15T00:00:00.000Z',
    '2026-03-10T00:00:00.000Z',
    '2026-03-24T00:00:00.000Z',
    '2026-04-05T00:00:00.000Z',
    '2026-04-20T00:00:00.000Z',
    '2026-05-15T00:00:00.000Z'
  ];

  const fallback: Application[] = [];

  for (let i = 0; i < 45; i++) {
    const school = dummySchools[i % dummySchools.length];
    const program = dummyPrograms[i % dummyPrograms.length];
    const status = statuses[i % statuses.length];
    const decisionDate = dates[i % dates.length];

    // Seed realistic GPA distributions (3.2 - 4.0)
    const gpa = Number((3.2 + (i % 9) * 0.1).toFixed(2));
    const publications = i % 4;

    fallback.push({
      id: `app-mock-${i}`,
      gpa: gpa > 4.0 ? 4.0 : gpa,
      publications: publications,
      school,
      program,
      decision: i % 8 === 0 ? null : { // 1 in 8 is pending (null decision)
        id: `dec-mock-${i}`,
        status,
        decisionDate
      }
    });
  }

  return fallback;
};

export default AnalyticsDashboard;
